[General]
; Version is for reference only
version = v0.7.0-20260531
; Possible clockrates: 1000000, 985248, 1022727, 1023440, 1022730
clock_rate = 985248
; Possible options: False, True
lock_clockrate = False
; Possible options: False, True
external_clock = False

[socketOne]
; Possible options: False, True
enabled = True
; Possible options: Disabled, Enabled
dualsid = Disabled
; Possible chiptypes: MOS, Unknown, SKPico, ARMSID, ARM2SID, FPGASID, RedipSID, PDSID, BackSID, SIDEmu
chiptype = SIDEmu
; Possible sidtypes: Unknown, N/A, 8580, 6581, FMOpl
sid1type = 8580
sid2type = N/A

[socketTwo]
; Possible options: False, True
enabled = True
; Possible options: Disabled, Enabled
dualsid = Enabled
; Possible chiptypes: MOS, Unknown, SKPico, ARMSID, ARM2SID, FPGASID, RedipSID, PDSID, BackSID, SIDEmu
chiptype = FPGASID
; Possible sidtypes: Unknown, N/A, 8580, 6581, FMOpl
sid1type = 8580
sid2type = 8580

[Features]
; Possible options: False, True
mirrored = False
flipped  = False
mixed    = False

[LED]
; Possible options: False, True
enabled = True
; Possible options: False, True
idle_breathe = True

[RGBLED]
; Possible options: False, True
enabled = True
; Possible options: False, True
idle_breathe = True
; Possible brightness values 0 ~ 255
brightness = 127
; Possible sids to use are 1, 2, 3 or 4
sid_to_use = 1

[FMOPL]
; Possible options: False, True
enabled = False

[Audioswitch]
; Possible options: Mono, Stereo
set_to = Mono
; Possible options: False, True
lock_audio_switch = False
